### ISSUE TITLE
linkify.js fails on every chat message

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-web-core#514]
```
index.js:821 Uncaught TypeError: e.linkify is not a function
    at oe.txtAddMsg (index.js:821:23)
    at oe.sendMsg (index.js:697:14)
    at HTMLTextAreaElement.<anonymous> (index.js:336:58)
```

**Comment by EdwardLu2018** [comment]
Fixed in 9a6d77483fe09ba5ad8f32867665699a2fadb85b
