### ISSUE TITLE
build page fails when no program objects in scene

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-web-core#664]
Sometime in recent build page program list changes the build page fails to load when there are no program objects in the scene: https://github.com/arenaxr/arena-web-core/compare/69a768297d3d984ac08bc7235a8c9504cc9c5361...ea985cc1a701e39e0201c2845edc96f193cc233d

Console:
```
persist-objects.js:783 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'firstChild')
    at populateProgramInstanceList (persist-objects.js:783:24)
    at updateSubscribeTopic (persist-objects.js:375:9)
    at Module.populateObjectList (persist-objects.js:364:5)
    at async main.js:999:9Understand this error
```

**Comment by mwfarb** [comment]
OK, not related to programs per se. There is a race condition now, when the build page loads sometimes it tries to mqtt subscribe before the mqtt connect finishes.
